export const weatherCodes = {
0: "Klar himmel",
1: "Främst klar",
2: "Delvis molnigt",
3: "Molnigt",
45: "Dimma",
48: "Rimfrostdimma",
51: "Lätt duggregn",
53: "Måttligt duggregn",
55: "Tät duggregn",
56: "Lätt frysduggregn",
57: "Tätt frysduggregn",
61: "Lätt regn",
63: "Måttligt regn",
65: "Kraftigt regn",
66: "Lätt frysningsregn",
67: "Kraftigt frysningsregn",
71: "Lätt snöfall",
73: "Måttligt snöfall",
75: "Kraftigt snöfall",
77: "Snöflingor",
80: "Lätta regnskurar",
81: "Måttliga regnskurar",
82: "Kraftiga regnskurar",
85: "Lätta snöskurar",
86: "Kraftiga snöskurar",
95: "Åskväder (lätt till måttligt)",
96: "Åskväder med lätt hagel",
99: "Åskväder med kraftigt hagel"
}